apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  image: quay.io/prometheus/prometheus:v2.30.1
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 1
  logLevel: debug
  retention: 2d
  routePrefix: /
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  version: v2.30.1
  serviceMonitorSelector:
    matchLabels:
      enabled: "true"
  podMonitorSelector:
    matchLabels:
      enabled: "true"
  remoteWrite:
    - url: http://a75c5cdb18eee4ea5a43b0dd90608b50-911352887.ap-south-1.elb.amazonaws.com/api/v1/write
  replicaExternalLabelName: "__replica__"
  externalLabels:
    cluster: "alice-saitama-dragon"